# Hardware-free fixtures: metadata and generated build graph, never a private sysroot.
cmake_minimum_required(VERSION 3.20)
if(NOT ROOT OR NOT SCRATCH OR NOT CASE)
    message(FATAL_ERROR "ROOT, SCRATCH and CASE are required")
endif()
file(REMOVE_RECURSE "${SCRATCH}")
file(MAKE_DIRECTORY "${SCRATCH}/project" "${SCRATCH}/rootfs/usr/lib/pkgconfig"
    "${SCRATCH}/rootfs/usr/include/fixture" "${SCRATCH}/host-pc")
set(_rootfs "${SCRATCH}/rootfs")
set(_pc "prefix=/usr\nlibdir=\${prefix}/lib\nincludedir=\${prefix}/include/fixture\nName: fixture\nDescription: public synthetic metadata\nVersion: 1.0\nLibs: -L\${libdir} -lfixture\nCflags: -I\${includedir}\n")
file(WRITE "${_rootfs}/usr/lib/libfixture.so" "")
foreach(_module gstreamer-1.0 gstreamer-app-1.0 gstreamer-video-1.0)
    file(WRITE "${_rootfs}/usr/lib/pkgconfig/${_module}.pc" "${_pc}")
    file(WRITE "${SCRATCH}/host-pc/${_module}.pc" "${_pc}")
endforeach()
set(ENV{PKG_CONFIG_PATH} "")
# Poison default/ambient discovery in every case: isolation must replace this directory.
set(ENV{PKG_CONFIG_LIBDIR} "${SCRATCH}/host-pc")
set(_expected 0)
set(_diagnostic "")
set(_project_kind "include")
if(CASE STREQUAL "host-path")
    set(ENV{PKG_CONFIG_PATH} "${SCRATCH}/host-pc")
    set(_expected 1)
    set(_diagnostic "AA_DECODE_PKG_ENV")
elseif(CASE STREQUAL "missing")
    # Frozen-sysroot reality: zero target GStreamer metadata -> explicitly UNAVAILABLE, no targets.
    file(REMOVE_RECURSE "${_rootfs}/usr/lib/pkgconfig")
    set(_project_kind "subdir")
elseif(CASE STREQUAL "escape")
    file(WRITE "${_rootfs}/usr/lib/pkgconfig/gstreamer-1.0.pc"
        "${_pc}Cflags: -I\${pc_sysrootdir}/../host-pc\n")
    set(_expected 1)
    set(_diagnostic "AA_DECODE_PKG_ESCAPE")
elseif(CASE STREQUAL "symlink")
    file(REMOVE "${_rootfs}/usr/lib/pkgconfig/gstreamer-1.0.pc")
    file(CREATE_LINK "${SCRATCH}/host-pc/gstreamer-1.0.pc"
        "${_rootfs}/usr/lib/pkgconfig/gstreamer-1.0.pc" SYMBOLIC)
    set(_expected 1)
    set(_diagnostic "AA_DECODE_PKG_ESCAPE")
elseif(CASE STREQUAL "unbound")
    set(_expected 1)
    set(_diagnostic "AA_DECODE_SYSROOT")
elseif(NOT CASE MATCHES "^(isolated|ordering)$")
    message(FATAL_ERROR "Unknown case: ${CASE}")
endif()
if(CASE STREQUAL "ordering")
    set(_project_kind "subdir")
endif()
if(_project_kind STREQUAL "subdir")
    set(_project "cmake_minimum_required(VERSION 3.20)\nproject(policy LANGUAGES CXX)\nenable_testing()\nfind_package(Python3 REQUIRED COMPONENTS Interpreter)\n")
else()
    set(_project "cmake_minimum_required(VERSION 3.20)\nproject(policy LANGUAGES NONE)\n")
endif()
string(APPEND _project "set(CMAKE_CROSSCOMPILING TRUE)\nset(CMAKE_SYSROOT \"${_rootfs}\")\nset(AA_SYSROOT_PAYLOAD \"${_rootfs}\")\nadd_custom_target(aa_sysroot_hash_gate COMMAND \"${CMAKE_COMMAND}\" -E false)\n")
if(CASE STREQUAL "unbound")
    string(APPEND _project "set(AA_SYSROOT_PAYLOAD \"${SCRATCH}\")\n")
endif()
if(_project_kind STREQUAL "subdir")
    string(APPEND _project "add_subdirectory(\"${ROOT}/tools/aa-decode-probe\" probe)\n")
else()
    string(APPEND _project "include(\"${ROOT}/cmake/DecodeDependencies.cmake\")\n")
    # Then successful discovery selects the fixture library, not ambient host metadata.
    string(APPEND _project "get_target_property(links PkgConfig::GST INTERFACE_LINK_LIBRARIES)\nif(NOT links STREQUAL \"${_rootfs}/usr/lib/libfixture.so\")\nmessage(FATAL_ERROR \"wrong library: \${links}\")\nendif()\n")
endif()
if(CASE STREQUAL "missing")
    # Then the explicitly unavailable probe registers no targets and reports its machine state.
    string(APPEND _project "foreach(_t aa-decode-probe decode-probe-inputs decode-probe-metrics decode-probe-discovery)\nif(TARGET \${_t})\nmessage(FATAL_ERROR \"probe target registered while unavailable: \${_t}\")\nendif()\nendforeach()\nif(NOT AA_DECODE_PROBE_CROSS STREQUAL \"UNAVAILABLE\")\nmessage(FATAL_ERROR \"expected AA_DECODE_PROBE_CROSS=UNAVAILABLE, got '\${AA_DECODE_PROBE_CROSS}'\")\nendif()\n")
endif()
file(WRITE "${SCRATCH}/project/CMakeLists.txt" "${_project}")
# When configuring with the actual dependency module.
execute_process(COMMAND "${CMAKE_COMMAND}" -S "${SCRATCH}/project" -B "${SCRATCH}/build" -G Ninja
    RESULT_VARIABLE _result OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
# Then poisoned inputs fail, while isolated target metadata succeeds.
if(_expected EQUAL 0)
    if(NOT _result EQUAL 0)
        message(FATAL_ERROR "Expected isolated configure success: ${_out}${_err}")
    endif()
else()
    if(_result EQUAL 0 OR NOT "${_out}${_err}" MATCHES "${_diagnostic}")
        message(FATAL_ERROR "Expected ${_diagnostic} rejection: ${_out}${_err}")
    endif()
endif()
if(CASE STREQUAL "missing")
    # Then the unavailable state is machine-visible and no probe tests are registered at all.
    if(NOT "${_out}${_err}" MATCHES "aa-decode-probe: UNAVAILABLE \\(target GStreamer dev metadata absent from frozen sysroot\\)")
        message(FATAL_ERROR "Missing UNAVAILABLE status message: ${_out}${_err}")
    endif()
    file(READ "${SCRATCH}/build/CMakeCache.txt" _cache)
    if(NOT _cache MATCHES "AA_DECODE_PROBE_CROSS:STRING=UNAVAILABLE")
        message(FATAL_ERROR "AA_DECODE_PROBE_CROSS not UNAVAILABLE in cache: ${_cache}")
    endif()
    if(EXISTS "${SCRATCH}/build/probe/CTestTestfile.cmake")
        file(READ "${SCRATCH}/build/probe/CTestTestfile.cmake" _tests)
        if(_tests MATCHES "add_test")
            message(FATAL_ERROR "Unavailable probe registered tests: ${_tests}")
        endif()
    endif()
endif()
if(CASE STREQUAL "ordering")
    file(READ "${SCRATCH}/build/probe/CTestTestfile.cmake" _tests)
    if(_tests MATCHES "add_test\\(\\[=\\[decode-probe")
        message(FATAL_ERROR "Cross build registered native executable tests")
    endif()
    foreach(_target aa-decode-probe decode-probe-inputs decode-probe-metrics decode-probe-discovery)
        if(NOT _tests MATCHES "cross_contamination_${_target}")
            message(FATAL_ERROR "Missing input provenance test: ${_target}")
        endif()
        # When directly building each target in parallel, the failing gate must run first.
        execute_process(COMMAND "${CMAKE_COMMAND}" --build "${SCRATCH}/build" --target "${_target}" --parallel 4
            RESULT_VARIABLE _built OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
        file(GLOB_RECURSE _objects "${SCRATCH}/build/*.o")
        # Then no object is compiled, even for targets with no GStreamer linkage.
        if(_built EQUAL 0 OR _objects OR NOT "${_out}${_err}" MATCHES "cmake -E false")
            message(FATAL_ERROR "Hash gate did not precede ${_target} compilation: ${_out}${_err}")
        endif()
    endforeach()
endif()
message(STATUS "PASS decode build policy ${CASE} (public fixture, not target acceptance)")
