# SPDX-License-Identifier: GPL-3.0-or-later
# Hardware-free fixtures: metadata and generated build graph, never a private sysroot.
cmake_minimum_required(VERSION 3.20)
if(NOT ROOT OR NOT SCRATCH OR NOT CASE)
    message(FATAL_ERROR "ROOT, SCRATCH and CASE are required")
endif()
file(REMOVE_RECURSE "${SCRATCH}")
file(MAKE_DIRECTORY "${SCRATCH}/project" "${SCRATCH}/rootfs/usr/lib/pkgconfig"
    "${SCRATCH}/rootfs/usr/include/fixture" "${SCRATCH}/host-pc")
set(_rootfs "${SCRATCH}/rootfs")
set(_pc "prefix=/usr\nlibdir=\${prefix}/lib\nincludedir=\${prefix}/include/fixture\nName: fixture\nDescription: public synthetic metadata\nVersion: 1.0\nLibs: -L\${libdir} -lfixture\nCflags: -I\${includedir}\n")
set(_ov_pc "prefix=/usr\nlibdir=\${prefix}/lib\nincludedir=\${prefix}/include/ov\nName: fixture\nDescription: public synthetic overlay metadata\nVersion: 1.0\nLibs: -L\${libdir} -lov\nCflags: -I\${includedir}\n")
# Overlay capture fixture: target-layout rootfs fragment, self-contained dev closure.
function(_aa_overlay_fixture _root)
    file(MAKE_DIRECTORY "${_root}/usr/lib/pkgconfig" "${_root}/usr/include/ov")
    file(WRITE "${_root}/usr/lib/libov.so" "")
    file(WRITE "${_root}/usr/include/ov/ov.h" "/* public synthetic overlay header */\n")
    foreach(_module IN LISTS ARGN)
        file(WRITE "${_root}/usr/lib/pkgconfig/${_module}.pc" "${_ov_pc}")
    endforeach()
endfunction()
file(WRITE "${_rootfs}/usr/lib/libfixture.so" "")
foreach(_module gstreamer-1.0 gstreamer-app-1.0 gstreamer-video-1.0)
    file(WRITE "${_rootfs}/usr/lib/pkgconfig/${_module}.pc" "${_pc}")
    file(WRITE "${SCRATCH}/host-pc/${_module}.pc" "${_pc}")
endforeach()
set(ENV{PKG_CONFIG_PATH} "")
# Poison default/ambient discovery in every case: isolation must replace this directory.
set(ENV{PKG_CONFIG_LIBDIR} "${SCRATCH}/host-pc")
set(_expected 0)
set(_diagnostic "")
set(_project_kind "include")
set(_overlay "")
if(CASE STREQUAL "host-path")
    set(ENV{PKG_CONFIG_PATH} "${SCRATCH}/host-pc")
    set(_expected 1)
    set(_diagnostic "AA_DECODE_PKG_ENV")
elseif(CASE STREQUAL "missing")
    # Frozen-sysroot reality: zero target GStreamer metadata -> explicitly UNAVAILABLE, no targets.
    file(REMOVE_RECURSE "${_rootfs}/usr/lib/pkgconfig")
    set(_project_kind "subdir")
elseif(CASE STREQUAL "partial")
    # Partial payload metadata is a fail-closed error, never an unavailable probe.
    file(REMOVE "${_rootfs}/usr/lib/pkgconfig/gstreamer-video-1.0.pc")
    set(_expected 1)
    set(_diagnostic "AA_DECODE_PKG_METADATA")
elseif(CASE MATCHES "^overlay")
    file(REMOVE_RECURSE "${_rootfs}/usr/lib/pkgconfig")
    set(_overlay "${SCRATCH}/overlay")
    if(CASE STREQUAL "overlay-partial")
        _aa_overlay_fixture("${_overlay}" gstreamer-1.0 gstreamer-app-1.0)
        set(_expected 1)
        set(_diagnostic "AA_DECODE_PKG_METADATA")
    elseif(CASE STREQUAL "overlay-escape")
        _aa_overlay_fixture("${_overlay}" gstreamer-1.0 gstreamer-app-1.0 gstreamer-video-1.0)
        file(REMOVE "${_overlay}/usr/lib/pkgconfig/gstreamer-1.0.pc")
        file(CREATE_LINK "${SCRATCH}/host-pc/gstreamer-1.0.pc"
            "${_overlay}/usr/lib/pkgconfig/gstreamer-1.0.pc" SYMBOLIC)
        set(_expected 1)
        set(_diagnostic "AA_DECODE_PKG_ESCAPE")
    elseif(CASE STREQUAL "overlay-poison")
        _aa_overlay_fixture("${_overlay}" gstreamer-1.0 gstreamer-app-1.0 gstreamer-video-1.0)
        file(WRITE "${SCRATCH}/host-pc/libhost-only.so" "")
        file(WRITE "${_overlay}/usr/lib/pkgconfig/gstreamer-1.0.pc"
            "${_ov_pc}Libs: ${SCRATCH}/host-pc/libhost-only.so\n")
        set(_expected 1)
        set(_diagnostic "AA_DECODE_PKG_ESCAPE")
    elseif(CASE STREQUAL "overlay-comma")
        # Contained, digest-recorded paths must not inject ld flags through -Wl commas.
        _aa_overlay_fixture("${_overlay}" gstreamer-1.0 gstreamer-app-1.0 gstreamer-video-1.0)
        file(MAKE_DIRECTORY "${_overlay}/usr/lib/x,-L,/usr/lib")
        file(WRITE "${_overlay}/usr/lib/x,-L,/usr/lib/libov.so" "")
        string(REPLACE "Libs: -L\${libdir} -lov" "Libs: -L\${libdir}/x,-L,/usr/lib -lov" _comma_pc "${_ov_pc}")
        foreach(_module gstreamer-1.0 gstreamer-app-1.0 gstreamer-video-1.0)
            file(WRITE "${_overlay}/usr/lib/pkgconfig/${_module}.pc" "${_comma_pc}")
        endforeach()
        set(_project_kind "subdir")
        set(_expected 1)
        set(_diagnostic "AA_DECODE_PKG_ESCAPE")
    elseif(CASE STREQUAL "overlay-semicolon")
        # Deep-escaped pkg-config semicolon survives discovery as one directory, then list-splits link options.
        _aa_overlay_fixture("${_overlay}" gstreamer-1.0 gstreamer-app-1.0 gstreamer-video-1.0)
        file(MAKE_DIRECTORY "${_overlay}/usr/lib/x;-L/usr/lib")
        file(WRITE "${_overlay}/usr/lib/x;-L/usr/lib/libov.so" "")
        # The overlay digest walk is itself list-valued; materialize the fragments
        # produced by splitting this adversarial relative path so it reaches discovery.
        file(MAKE_DIRECTORY "${_overlay}/-L/usr/lib" "${_overlay}/usr/lib/x")
        file(WRITE "${_overlay}/-L/usr/lib/libov.so" "")
        set(_pc_semicolon_escape "\\")
        string(REPEAT "${_pc_semicolon_escape}" 4 _pc_semicolon_escape)
        string(REPLACE "Libs: -L\${libdir} -lov"
            "Libs: -L\${libdir}/x${_pc_semicolon_escape};-L/usr/lib -lov"
            _semicolon_pc "${_ov_pc}")
        foreach(_module gstreamer-1.0 gstreamer-app-1.0 gstreamer-video-1.0)
            file(WRITE "${_overlay}/usr/lib/pkgconfig/${_module}.pc" "${_semicolon_pc}")
        endforeach()
        set(_project_kind "subdir")
        set(_expected 1)
        set(_diagnostic "AA_DECODE_PKG_ESCAPE")
    elseif(CASE MATCHES "^overlay-(mismatch|extra|available)$")
        _aa_overlay_fixture("${_overlay}" gstreamer-1.0 gstreamer-app-1.0 gstreamer-video-1.0)
        set(_project_kind "subdir")
    elseif(CASE STREQUAL "overlay")
        # Well-formed capture over a frozen payload: probe AVAILABLE from the overlay root.
        _aa_overlay_fixture("${_overlay}" gstreamer-1.0 gstreamer-app-1.0 gstreamer-video-1.0)
        set(_project_kind "subdir")
    else()
        message(FATAL_ERROR "Unknown overlay case: ${CASE}")
    endif()
elseif(CASE STREQUAL "escape")
    file(WRITE "${_rootfs}/usr/lib/pkgconfig/gstreamer-1.0.pc"
        "${_pc}Cflags: -I\${pc_sysrootdir}/../host-pc\n")
    set(_expected 1)
    set(_diagnostic "AA_DECODE_PKG_ESCAPE")
elseif(CASE STREQUAL "symlink")
    file(REMOVE "${_rootfs}/usr/lib/pkgconfig/gstreamer-1.0.pc")
    file(CREATE_LINK "${SCRATCH}/host-pc/gstreamer-1.0.pc"
        "${_rootfs}/usr/lib/pkgconfig/gstreamer-1.0.pc" SYMBOLIC)
    set(_expected 1)
    set(_diagnostic "AA_DECODE_PKG_ESCAPE")
elseif(CASE STREQUAL "unbound")
    set(_expected 1)
    set(_diagnostic "AA_DECODE_SYSROOT")
elseif(NOT CASE MATCHES "^(isolated|ordering)$")
    message(FATAL_ERROR "Unknown case: ${CASE}")
endif()
if(CASE STREQUAL "ordering")
    set(_project_kind "subdir")
endif()
if(_project_kind STREQUAL "subdir")
    set(_project "cmake_minimum_required(VERSION 3.20)\nproject(policy LANGUAGES CXX)\nenable_testing()\nfind_package(Python3 REQUIRED COMPONENTS Interpreter)\n")
else()
    set(_project "cmake_minimum_required(VERSION 3.20)\nproject(policy LANGUAGES NONE)\n")
endif()
string(APPEND _project "set(CMAKE_CROSSCOMPILING TRUE)\nset(CMAKE_SYSROOT \"${_rootfs}\")\nset(AA_SYSROOT_PAYLOAD \"${_rootfs}\")\nadd_custom_target(aa_sysroot_hash_gate COMMAND \"${CMAKE_COMMAND}\" -E false)\n")
# Given the real toolchain's root-only discovery policy, absolute overlay -L paths
# must resolve without granting access to paths outside the two sanctioned roots.
string(APPEND _project "set(CMAKE_FIND_ROOT_PATH \"${_rootfs}\")\nset(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)\nset(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)\nset(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)\nset(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)\n")
if(CASE STREQUAL "unbound")
    string(APPEND _project "set(AA_SYSROOT_PAYLOAD \"${SCRATCH}\")\n")
endif()
if(_overlay)
    string(APPEND _project "set(AA_DECODE_GST_OVERLAY \"${_overlay}\")\n")
endif()
if(_project_kind STREQUAL "subdir")
    if(CASE STREQUAL "overlay")
        # Top-scope discovery so PkgConfig::GST is visible to the assertions below; the probe
        # subdirectory re-runs the same module in its own scope while registering targets.
        string(APPEND _project "include(\"${ROOT}/cmake/DecodeDependencies.cmake\")\n")
    endif()
    string(APPEND _project "add_subdirectory(\"${ROOT}/tools/aa-decode-probe\" probe)\n")
else()
    string(APPEND _project "include(\"${ROOT}/cmake/DecodeDependencies.cmake\")\n")
    # Then successful discovery selects the fixture library, not ambient host metadata.
    string(APPEND _project "get_target_property(links PkgConfig::GST INTERFACE_LINK_LIBRARIES)\nif(NOT links STREQUAL \"${_rootfs}/usr/lib/libfixture.so\")\nmessage(FATAL_ERROR \"wrong library: \${links}\")\nendif()\n")
endif()
if(CASE STREQUAL "missing")
    # Then the explicitly unavailable probe registers no targets and reports its machine state.
    string(APPEND _project "foreach(_t aa-decode-probe decode-probe-inputs decode-probe-metrics decode-probe-discovery)\nif(TARGET \${_t})\nmessage(FATAL_ERROR \"probe target registered while unavailable: \${_t}\")\nendif()\nendforeach()\nif(NOT AA_DECODE_PROBE_CROSS STREQUAL \"UNAVAILABLE\")\nmessage(FATAL_ERROR \"expected AA_DECODE_PROBE_CROSS=UNAVAILABLE, got '\${AA_DECODE_PROBE_CROSS}'\")\nendif()\n")
elseif(CASE STREQUAL "overlay")
    # Then a well-formed overlay marks the probe AVAILABLE and supplies its inputs.
    string(APPEND _project "if(NOT CMAKE_FIND_ROOT_PATH STREQUAL \"${_rootfs}\")\nmessage(FATAL_ERROR \"decode discovery changed caller find roots\")\nendif()\n")
    string(APPEND _project "if(NOT AA_DECODE_PROBE_CROSS STREQUAL \"AVAILABLE\")\nmessage(FATAL_ERROR \"expected AA_DECODE_PROBE_CROSS=AVAILABLE, got '\${AA_DECODE_PROBE_CROSS}'\")\nendif()\nif(NOT TARGET aa-decode-probe)\nmessage(FATAL_ERROR \"probe target missing in AVAILABLE cross mode\")\nendif()\nget_target_property(links PkgConfig::GST INTERFACE_LINK_LIBRARIES)\nif(NOT links STREQUAL \"${_overlay}/usr/lib/libov.so\")\nmessage(FATAL_ERROR \"wrong library: \${links}\")\nendif()\n")
endif()
file(WRITE "${SCRATCH}/project/CMakeLists.txt" "${_project}")
if(CASE MATCHES "^overlay-(mismatch|extra|available)$")
    # Given a real probe build graph, the overlay gate must precede every consumer.
    string(REPLACE "-E false" "-E true" _project "${_project}")
    file(WRITE "${SCRATCH}/project/CMakeLists.txt" "${_project}")
    file(APPEND "${SCRATCH}/project/CMakeLists.txt"
        "if(NOT AA_DECODE_PROBE_CROSS STREQUAL \"AVAILABLE\" OR NOT TARGET aa-decode-probe)\nmessage(FATAL_ERROR \"AA_DECODE_AVAILABLE_REQUIRED\")\nendif()\n")
endif()
# When configuring with the actual dependency module.
execute_process(COMMAND "${CMAKE_COMMAND}" -S "${SCRATCH}/project" -B "${SCRATCH}/build" -G Ninja
    RESULT_VARIABLE _result OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
# Then poisoned inputs fail, while isolated target metadata succeeds.
if(_expected EQUAL 0)
    if(NOT _result EQUAL 0)
        message(FATAL_ERROR "Expected isolated configure success: ${_out}${_err}")
    endif()
else()
    if(_result EQUAL 0 OR NOT "${_out}${_err}" MATCHES "${_diagnostic}")
        message(FATAL_ERROR "Expected ${_diagnostic} rejection: ${_out}${_err}")
    endif()
endif()
if(CASE STREQUAL "missing")
    # Then the unavailable state is machine-visible and no probe tests are registered at all.
    if(NOT "${_out}${_err}" MATCHES "aa-decode-probe: UNAVAILABLE \\(target GStreamer dev metadata absent from frozen sysroot\\)")
        message(FATAL_ERROR "Missing UNAVAILABLE status message: ${_out}${_err}")
    endif()
    file(READ "${SCRATCH}/build/CMakeCache.txt" _cache)
    if(NOT _cache MATCHES "AA_DECODE_PROBE_CROSS:STRING=UNAVAILABLE")
        message(FATAL_ERROR "AA_DECODE_PROBE_CROSS not UNAVAILABLE in cache: ${_cache}")
    endif()
    if(EXISTS "${SCRATCH}/build/probe/CTestTestfile.cmake")
        file(READ "${SCRATCH}/build/probe/CTestTestfile.cmake" _tests)
        if(_tests MATCHES "add_test")
            message(FATAL_ERROR "Unavailable probe registered tests: ${_tests}")
        endif()
    endif()
endif()
if(CASE STREQUAL "overlay")
    # Then the AVAILABLE state and the configure-time input digest are machine-visible.
    file(READ "${SCRATCH}/build/CMakeCache.txt" _cache)
    if(NOT _cache MATCHES "AA_DECODE_PROBE_CROSS:STRING=AVAILABLE")
        message(FATAL_ERROR "AA_DECODE_PROBE_CROSS not AVAILABLE in cache: ${_cache}")
    endif()
    if(NOT _cache MATCHES "AA_DECODE_GST_OVERLAY_DIGEST:STRING=([0-9a-f]+)")
        message(FATAL_ERROR "overlay input digest missing from cache: ${_cache}")
    endif()
    set(_digest_first "${CMAKE_MATCH_1}")
    # Then the digest binds overlay input content at configure time.
    file(APPEND "${_overlay}/usr/include/ov/ov.h" "/* tampered input */\n")
    execute_process(COMMAND "${CMAKE_COMMAND}" -S "${SCRATCH}/project" -B "${SCRATCH}/build" -G Ninja
        RESULT_VARIABLE _re OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
    if(NOT _re EQUAL 0)
        message(FATAL_ERROR "Reconfigure after overlay input change failed: ${_out}${_err}")
    endif()
    file(READ "${SCRATCH}/build/CMakeCache.txt" _cache)
    if(NOT _cache MATCHES "AA_DECODE_GST_OVERLAY_DIGEST:STRING=([0-9a-f]+)")
        message(FATAL_ERROR "overlay input digest missing after reconfigure: ${_cache}")
    endif()
    if("${CMAKE_MATCH_1}" STREQUAL "${_digest_first}")
        message(FATAL_ERROR "overlay digest did not bind tampered input content")
    endif()
endif()
if(CASE STREQUAL "ordering")
    file(READ "${SCRATCH}/build/probe/CTestTestfile.cmake" _tests)
    if(_tests MATCHES "add_test\\(\\[=\\[decode-probe")
        message(FATAL_ERROR "Cross build registered native executable tests")
    endif()
    foreach(_target aa-decode-probe decode-probe-inputs decode-probe-metrics decode-probe-discovery)
        if(NOT _tests MATCHES "cross_contamination_${_target}")
            message(FATAL_ERROR "Missing input provenance test: ${_target}")
        endif()
        # When directly building each target in parallel, the failing gate must run first.
        execute_process(COMMAND "${CMAKE_COMMAND}" --build "${SCRATCH}/build" --target "${_target}" --parallel 4
            RESULT_VARIABLE _built OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
        file(GLOB_RECURSE _objects "${SCRATCH}/build/*.o")
        # Then no object is compiled, even for targets with no GStreamer linkage.
        if(_built EQUAL 0 OR _objects OR NOT "${_out}${_err}" MATCHES "cmake -E false")
            message(FATAL_ERROR "Hash gate did not precede ${_target} compilation: ${_out}${_err}")
        endif()
    endforeach()
endif()
if(CASE MATCHES "^overlay-(mismatch|extra|available)$")
    # When an input changes after configure, direct parallel builds must fail before objects.
    if(CASE STREQUAL "overlay-mismatch")
        file(APPEND "${_overlay}/usr/include/ov/ov.h" "/* changed after configure */\n")
    elseif(CASE STREQUAL "overlay-extra")
        file(WRITE "${_overlay}/.extra-header" "unrecorded input\n")
    endif()
    if(CASE STREQUAL "overlay-available")
        execute_process(COMMAND "${CMAKE_COMMAND}" --build "${SCRATCH}/build"
            --target aa_decode_overlay_hash_gate RESULT_VARIABLE _built OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
        if(NOT _built EQUAL 0 OR NOT "${_out}${_err}" MATCHES "AA_DECODE_OVERLAY_VERIFIED")
            message(FATAL_ERROR "Overlay AVAILABLE gate failed: ${_out}${_err}")
        endif()
        file(READ "${SCRATCH}/build/aa-decode-overlay.sha256" _manifest)
        string(SHA256 _digest "${_manifest}")
        file(READ "${SCRATCH}/build/CMakeCache.txt" _cache)
        if(NOT _cache MATCHES "AA_DECODE_GST_OVERLAY_DIGEST:STRING=${_digest}")
            message(FATAL_ERROR "Overlay AVAILABLE manifest/cache binding failed")
        endif()
    else()
        foreach(_target aa-decode-probe decode-probe-inputs decode-probe-metrics decode-probe-discovery)
            execute_process(COMMAND "${CMAKE_COMMAND}" --build "${SCRATCH}/build" --target "${_target}" --parallel 4
                RESULT_VARIABLE _built OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
            file(GLOB_RECURSE _objects "${SCRATCH}/build/*.o")
            # Then the overlay mismatch alone rejects the build before compilation.
            if(_built EQUAL 0 OR _objects OR NOT "${_out}${_err}" MATCHES "AA_DECODE_OVERLAY_MISMATCH")
                message(FATAL_ERROR "Overlay gate did not precede ${_target}: ${_out}${_err}")
            endif()
        endforeach()
    endif()
endif()
message(STATUS "PASS decode build policy ${CASE} (public fixture, not target acceptance)")
