# GNU compiler intrinsics are toolchain inputs, not acquired Jetson runtime inputs.
# Explicit startup/library inputs plus ld -nostdlib prevent missing target files
# from falling back to the host-installed /usr/aarch64-linux-gnu runtime.
if(NOT CMAKE_SYSROOT)
    message(FATAL_ERROR "AA_RUNTIME_READY: AA_SYSROOT_ROOTFS is required")
endif()
get_filename_component(CMAKE_SYSROOT "${CMAKE_SYSROOT}" REALPATH)
foreach(_aa_env CPATH C_INCLUDE_PATH CPLUS_INCLUDE_PATH LIBRARY_PATH GCC_EXEC_PREFIX COMPILER_PATH)
    if(NOT "$ENV{${_aa_env}}" STREQUAL "")
        message(FATAL_ERROR "AA_RUNTIME_ENV: clear ${_aa_env} for an isolated cross build")
    endif()
endforeach()
execute_process(COMMAND "${CMAKE_CXX_COMPILER}" -print-file-name=include
    OUTPUT_VARIABLE _aa_builtin OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
execute_process(COMMAND "${CMAKE_CXX_COMPILER}" -print-libgcc-file-name
    OUTPUT_VARIABLE _aa_libgcc OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
get_filename_component(_aa_support "${_aa_libgcc}" DIRECTORY)
set(_aa_lib "${CMAKE_SYSROOT}/usr/lib/aarch64-linux-gnu")
if(NOT EXISTS "${_aa_lib}/crt1.o")
    set(_aa_lib "${CMAKE_SYSROOT}/usr/lib")
endif()
set(_aa_cpp "${CMAKE_SYSROOT}/usr/include/c++/13")
set(_aa_stdcpp "${CMAKE_SYSROOT}/usr/lib/gcc/aarch64-linux-gnu/13/libstdc++.so")
if(NOT EXISTS "${_aa_stdcpp}")
    set(_aa_stdcpp "${_aa_lib}/libstdc++.so")
endif()
set(_aa_cpp_arch "${CMAKE_SYSROOT}/usr/include/aarch64-linux-gnu/c++/13")
if(NOT EXISTS "${_aa_cpp_arch}/bits/c++config.h")
    set(_aa_cpp_arch "${_aa_cpp}/aarch64-linux-gnu")
endif()
foreach(_aa_required "${CMAKE_SYSROOT}/usr/include/stdio.h" "${CMAKE_SYSROOT}/usr/include/stdc-predef.h"
        "${_aa_cpp}/vector" "${_aa_cpp_arch}/bits/c++config.h"
        "${_aa_lib}/crt1.o" "${_aa_lib}/crti.o" "${_aa_lib}/crtn.o"
        "${_aa_lib}/libc.so" "${_aa_lib}/libm.so" "${_aa_stdcpp}" "${_aa_lib}/libgcc_s.so.1"
        "${_aa_support}/crtbegin.o" "${_aa_support}/crtend.o" "${_aa_libgcc}")
    if(NOT EXISTS "${_aa_required}")
        message(FATAL_ERROR "AA_RUNTIME_READY: missing ${_aa_required}; no host cross-runtime fallback")
    endif()
    string(FIND "${_aa_required}" "${CMAKE_SYSROOT}/" _aa_target_input)
    if(_aa_target_input EQUAL 0)
        get_filename_component(_aa_resolved "${_aa_required}" REALPATH)
        string(FIND "${_aa_resolved}" "${CMAKE_SYSROOT}/" _aa_inside)
        if(NOT _aa_inside EQUAL 0)
            message(FATAL_ERROR "AA_RUNTIME_READY: target input escapes sysroot: ${_aa_required}")
        endif()
    endif()
endforeach()
set(_aa_c "-nostdinc -isystem \"${_aa_builtin}\" -isystem \"${CMAKE_SYSROOT}/usr/include/aarch64-linux-gnu\" -isystem \"${CMAKE_SYSROOT}/usr/include\"")
set(CMAKE_C_FLAGS_INIT "${_aa_c}")
set(CMAKE_CXX_FLAGS_INIT "-nostdinc++ -isystem \"${_aa_cpp}\" -isystem \"${_aa_cpp_arch}\" -isystem \"${_aa_cpp}/backward\" ${_aa_c}")
set(_aa_link "-nostdlib -Wl,-nostdlib -B\"${_aa_lib}/\" -L\"${_aa_lib}\" -L\"${CMAKE_SYSROOT}/lib/aarch64-linux-gnu\" -L\"${CMAKE_SYSROOT}/lib\"")
set(CMAKE_EXE_LINKER_FLAGS_INIT "${_aa_link} -no-pie \"${_aa_lib}/crt1.o\" \"${_aa_lib}/crti.o\" \"${_aa_support}/crtbegin.o\"")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "${_aa_link} \"${_aa_lib}/crti.o\" \"${_aa_support}/crtbeginS.o\"")
set(CMAKE_MODULE_LINKER_FLAGS_INIT "${CMAKE_SHARED_LINKER_FLAGS_INIT}")
set(_aa_libraries "\"${_aa_libgcc}\" \"${_aa_lib}/libgcc_s.so.1\" \"${_aa_lib}/libm.so\" \"${_aa_lib}/libc.so\" \"${_aa_libgcc}\" \"${_aa_support}/crtend.o\" \"${_aa_lib}/crtn.o\"")
set(CMAKE_C_STANDARD_LIBRARIES_INIT "${_aa_libraries}")
set(CMAKE_CXX_STANDARD_LIBRARIES_INIT "\"${_aa_stdcpp}\" ${_aa_libraries}")
# Keep dependency files including system headers alongside every actual object.
set(CMAKE_C_COMPILE_OBJECT "<CMAKE_C_COMPILER> <DEFINES> <INCLUDES> <FLAGS> -Wp,-MD,<OBJECT>.headers.d -o <OBJECT> -c <SOURCE>")
set(CMAKE_CXX_COMPILE_OBJECT "<CMAKE_CXX_COMPILER> <DEFINES> <INCLUDES> <FLAGS> -Wp,-MD,<OBJECT>.headers.d -o <OBJECT> -c <SOURCE>")
