file(READ "${BUILD}/compile_commands.json" commands)
string(JSON count LENGTH "${commands}")
math(EXPR last "${count} - 1")
set(sdk_count 0)
set(proto_count 0)
set(consumer_count 0)
foreach(index RANGE ${last})
    string(JSON source GET "${commands}" ${index} file)
    string(JSON command GET "${commands}" ${index} command)
    if(source MATCHES "/aasdk/src/.*\\.cpp$" OR source MATCHES "\\.pb\\.cc$" OR source MATCHES "/tests/(aasdk/consumer|host/smoke)\\.cpp$")
        if(NOT command MATCHES "-std=c\\+\\+20( |$)" OR command MATCHES "-std=(gnu\\+\\+|c\\+\\+)(14|17)( |$)")
            message(FATAL_ERROR "Actual compile standard not C++20: ${command}")
        endif()
        if(source MATCHES "/aasdk/src/")
            list(APPEND compiled_sources "${source}")
            math(EXPR sdk_count "${sdk_count} + 1")
        elseif(source MATCHES "\\.pb\\.cc$")
            math(EXPR proto_count "${proto_count} + 1")
        elseif(source MATCHES "/aasdk/consumer\\.cpp$")
            math(EXPR consumer_count "${consumer_count} + 1")
        endif()
    endif()
endforeach()
file(GLOB_RECURSE production_sources "${STAGE}/aasdk/src/*.cpp")
list(FILTER production_sources EXCLUDE REGEX "\\.ut\\.cpp$")
list(SORT production_sources)
list(SORT compiled_sources)
file(GLOB_RECURSE schemas "${STAGE}/aasdk/protobuf/*.proto")
list(LENGTH schemas schema_count)
if(NOT compiled_sources STREQUAL production_sources OR NOT proto_count EQUAL schema_count OR NOT consumer_count EQUAL 1)
    message(FATAL_ERROR "Incomplete production source/schema/consumer inventory")
endif()
message(STATUS "Actual C++20 commands: production=${sdk_count}, generated=${proto_count}, consumer=${consumer_count}; complete staged source coverage")
