# SPDX-License-Identifier: GPL-3.0-or-later
foreach(binary "${CONSUMER}" "${SDK}" "${PROTO}")
    execute_process(COMMAND "${NM}" -C --defined-only "${binary}"
        RESULT_VARIABLE result OUTPUT_VARIABLE defined ERROR_VARIABLE error)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "nm -C failed: ${error}")
    endif()
    file(WRITE "${binary}.nm-defined.txt" "${defined}")
    execute_process(COMMAND "${NM}" -C -u "${binary}"
        RESULT_VARIABLE result OUTPUT_VARIABLE undefined ERROR_VARIABLE error)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "nm -C -u failed: ${error}")
    endif()
    file(WRITE "${binary}.nm-undefined.txt" "${undefined}")
    # Dynamic imports are legitimate if the actual loader resolves them.
    execute_process(COMMAND ldd -r "${binary}"
        RESULT_VARIABLE result OUTPUT_VARIABLE loaded ERROR_VARIABLE error)
    if(NOT result EQUAL 0 OR "${loaded}${error}" MATCHES "undefined symbol|not found")
        message(FATAL_ERROR "Unresolved dynamic boundary: ${loaded}${error}")
    endif()
    file(WRITE "${binary}.ldd.txt" "${loaded}${error}")
    if(binary STREQUAL SDK)
        foreach(symbol "aasdk::transport::SSLWrapper::getMethod" "aasdk::messenger::Cryptor::isActive" "aasdk::messenger::Cryptor::Cryptor")
            if(NOT defined MATCHES "${symbol}")
                message(FATAL_ERROR "Missing production definition: ${symbol}")
            endif()
        endforeach()
    elseif(binary STREQUAL CONSUMER)
        foreach(symbol "aasdk::transport::SSLWrapper::getMethod" "aasdk::messenger::Cryptor::isActive" "aasdk::messenger::Cryptor::Cryptor")
            if(NOT undefined MATCHES "${symbol}")
                message(FATAL_ERROR "Consumer did not link out-of-line boundary: ${symbol}")
            endif()
        endforeach()
    endif()
endforeach()
message(STATUS "nm -C proves production definitions and real consumer imports; ldd -r resolves all dynamic system and SDK imports")
