// SPDX-License-Identifier: GPL-3.0-or-later
#pragma once

// Pre-28 wire-conformance fixtures: INDEPENDENTLY SPECIFIED raw bytes (task:
// decision-oaa-aasdk-conformance.json action item 3).
//
// DERIVATION CONTRACT (why these bytes are independent):
//   Every literal below was hand-assembled from (a) the OAA wire rulebook
//   mrmees/open-android-auto@61eab61c5f9968154ff1a80faa8c0a427b208479
//   (file:line cited per fixture) and (b) first-principles protobuf-2 wire
//   encoding (tag = field<<3|wire_type; varint little-endian base-128; sint32
//   zigzag; negative int32/enum sign-extended to a 10-byte varint; LEN =
//   tag, varint length, bytes). They were NOT produced by our adapter, by the
//   generated AASDK serializers, or by any run of our code. Tests then compare
//   the adapter's encode/decode against these literals (round-trip and
//   exact-byte where the spec is unambiguous) so any divergence fails closed.
//
//   Frame wrappers are hand-derived from docs/channels/architecture.md:35-101
//   (rulebook) which matches pinned aasdk FrameType/MessageType/EncryptionType:
//   [channel:1][flags:1][size:2 BE][payload]; flags 0x07 = PLAIN|CONTROL|BULK,
//   0x03 = PLAIN|SPECIFIC|BULK.
//
// Fixture files (task-20 aa-replay-fixture-v1 envelope, SHA-256 pinned) live in
// tests/replay/fixtures/conformance/ and are regenerated by
// aa_conformance_fixture_write from exactly these bytes; the envelope is
// container plumbing, the payload bytes are this spec.
//
// Directions are the HU's view per the OAA wire truth (see
// wire-conformance-matrix rows R01-R36); where OAA self-contradicts, the 17.3
// endpoint ledger / gold proto comments win and the conflict is recorded in the
// matrix discrepancy ledger.

#include <array>
#include <cstddef>
#include <cstdint>
#include <span>
#include <string_view>
#include <vector>

namespace conformancewire {

// Hex helpers used by tests and the fixture writer.
[[nodiscard]] inline std::vector<std::byte> bytes(std::initializer_list<std::uint8_t> values) {
    std::vector<std::byte> out;
    out.reserve(values.size());
    for (const auto value : values) {
        out.push_back(static_cast<std::byte>(value));
    }
    return out;
}

// ---------------------------------------------------------------------------
// F-A VersionRequest v1.1 (control 0x0001, HU -> phone)
// Derivation: OAA docs/interactions/02-version-ssl-auth.md:83-98 (observed
// example "HU sends: 00 01 00 01 00 01"). Body is raw binary: major BE16=1,
// minor BE16=1. NOT protobuf.
// ---------------------------------------------------------------------------
inline const std::vector<std::byte> F_A_version_request_v1_1_payload =
    bytes({0x00, 0x01, 0x00, 0x01, 0x00, 0x01});
// Frame: channel 0, flags 0x07 (PLAIN|CONTROL|BULK), size BE16 = 6.
inline const std::vector<std::byte> F_A_version_request_v1_1_frame =
    bytes({0x00, 0x07, 0x00, 0x06, 0x00, 0x01, 0x00, 0x01, 0x00, 0x01});

// ---------------------------------------------------------------------------
// F-B VersionResponse v1.7 MATCH (control 0x0002, phone -> HU)
// Derivation: OAA docs/interactions/02-version-ssl-auth.md:103-125 (observed
// example "Phone responds: 00 02 00 01 00 07 00 00"). Body: major=1, minor=7,
// status=0x0000. NOTE: requests >= v1.6 append a WireConfig tail (OAA
// 02:139-141) - the 8-byte form is the v<1.6 / legacy-response core only
// (discrepancy D15). Our adapter has NO response codec (matrix R02: absent).
// ---------------------------------------------------------------------------
inline const std::vector<std::byte> F_B_version_response_v1_7_payload =
    bytes({0x00, 0x02, 0x00, 0x01, 0x00, 0x07, 0x00, 0x00});
inline const std::vector<std::byte> F_B_version_response_v1_7_frame =
    bytes({0x00, 0x07, 0x00, 0x08, 0x00, 0x02, 0x00, 0x01, 0x00, 0x07, 0x00, 0x00});

// ---------------------------------------------------------------------------
// F-D ServiceDiscoveryRequest (control 0x0005, phone -> HU) - device info
// Derivation: OAA oaa/control/ServiceDiscoveryRequestMessage.proto:15-20.
//   f4 device_name "Pixel": tag (4<<3|2)=0x22, len 5, ASCII.
//   f5 device_brand "google": tag (5<<3|2)=0x2A, len 6, ASCII.
// (Pinned-AASDK names f4 label_text / f5 device_name - semantic shift D8; the
// OAA naming is live-capture confirmed and is the wire truth.)
// ---------------------------------------------------------------------------
inline const std::vector<std::byte> F_D_service_discovery_request_payload =
    bytes({0x00, 0x05,
           0x22, 0x05, 'P', 'i', 'x', 'e', 'l',
           0x2A, 0x06, 'g', 'o', 'o', 'g', 'l', 'e'});
inline const std::vector<std::byte> F_D_service_discovery_request_frame =
    bytes({0x00, 0x07, 0x00, 0x0F,
           0x00, 0x05,
           0x22, 0x05, 'P', 'i', 'x', 'e', 'l',
           0x2A, 0x06, 'g', 'o', 'o', 'g', 'l', 'e'});

// ---------------------------------------------------------------------------
// F-E ServiceDiscoveryResponse (control 0x0006, HU -> phone) - one video svc
// Derivation: oaa/control/ServiceDiscoveryResponseMessage.proto:34 +
// oaa/control/ChannelDescriptorData.proto:50-54 + oaa/av/AVChannelData.proto
// (stream_type 1, video_configs 4) + oaa/video/VideoConfigData.proto:20-30 +
// oaa/av/MediaCodecTypeEnum.proto. Service entry:
//   Service.f1 id = 99        -> 08 63
//   Service.f3 media_sink     -> 1A 0A
//     MediaSink.f1 available_type = H264_BP(3) -> 08 03
//     MediaSink.f4 video_configs  -> 22 06
//       VideoConfig.f1 resolution = 1280x720(2) -> 08 02
//       VideoConfig.f2 fps        = 30(2)       -> 10 02
//       VideoConfig.f10 codec     = H264_BP(3)  -> 50 03
// Response.f1 channels -> 0A 10 wrapping the 14-byte Service
// (Service body = 08 63 1A 0A 08 03 22 06 08 02 10 02 50 03 = 14 bytes).
// Enum values match BOTH rulebooks (matrix R04): resolution 2 = 1280x720,
// fps 2 = 30, codec 3 = H264_BP.
// ---------------------------------------------------------------------------
inline const std::vector<std::byte> F_E_service_discovery_response_payload =
    bytes({0x00, 0x06,
           0x0A, 0x0E,
             0x08, 0x63,
             0x1A, 0x0A,
               0x08, 0x03,
               0x22, 0x06,
                 0x08, 0x02,
                 0x10, 0x02,
                 0x50, 0x03});
inline const std::vector<std::byte> F_E_service_discovery_response_frame =
    bytes({0x00, 0x07, 0x00, 0x12,
           0x00, 0x06,
           0x0A, 0x0E,
             0x08, 0x63,
             0x1A, 0x0A,
               0x08, 0x03,
               0x22, 0x06,
                 0x08, 0x02,
                 0x10, 0x02,
                 0x50, 0x03});

// ---------------------------------------------------------------------------
// F-F ChannelOpenRequest (control 0x0007, phone -> HU)
// Derivation: oaa/control/ChannelOpenRequestMessage.proto:20-22.
//   f1 priority = 1000 as sint32 zigzag: (1000<<1) = 2000 = varint D0 0F
//     -> 08 D0 0F
//   f2 service_id = 99 -> 10 63
// ---------------------------------------------------------------------------
inline const std::vector<std::byte> F_F_channel_open_request_payload =
    bytes({0x00, 0x07, 0x08, 0xD0, 0x0F, 0x10, 0x63});
inline const std::vector<std::byte> F_F_channel_open_request_frame =
    bytes({0x00, 0x07, 0x00, 0x07, 0x00, 0x07, 0x08, 0xD0, 0x0F, 0x10, 0x63});

// ---------------------------------------------------------------------------
// F-G ChannelOpenResponse SUCCESS (control 0x0008, HU -> phone)
// Derivation: f1 status = 0 (OK / STATUS_SUCCESS) -> 08 00.
// ---------------------------------------------------------------------------
inline const std::vector<std::byte> F_G_channel_open_response_success_payload =
    bytes({0x00, 0x08, 0x08, 0x00});
inline const std::vector<std::byte> F_G_channel_open_response_success_frame =
    bytes({0x00, 0x07, 0x00, 0x04, 0x00, 0x08, 0x08, 0x00});

// ---------------------------------------------------------------------------
// F-H ChannelOpenResponse COMMAND_NOT_SUPPORTED (status = -250)
// Derivation: proto2 enum negatives serialize as int32 sign-extended to a
// 64-bit varint. -250 = 0xFFFFFFFFFFFFFF06; 7-bit groups LSB-first are
// 06 | 7E | 7F x7 | 01 (bit 7 of the value is 0, so group 1 is 0x7E) = 10
// bytes: 86 FE FF FF FF FF FF FF FF 01. Values agree across rulebooks
// (COMMAND_NOT_SUPPORTED = -250: OAA oaa/common/StatusEnum.proto:44, AASDK
// shared/MessageStatus.proto:33).
// ---------------------------------------------------------------------------
inline const std::vector<std::byte> F_H_channel_open_response_unsupported_payload =
    bytes({0x00, 0x08, 0x08, 0x86, 0xFE, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0x01});
inline const std::vector<std::byte> F_H_channel_open_response_unsupported_frame =
    bytes({0x00, 0x07, 0x00, 0x0D,
           0x00, 0x08, 0x08, 0x86, 0xFE, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0x01});

// ---------------------------------------------------------------------------
// F-I PingRequest (control 0x000B, phone -> HU)
// Derivation: PingRequest{f1 timestamp=42 (08 2A), f2 bug_report=true
// (10 01), f3 data = DE AD (1A 02 DE AD)}.
// ---------------------------------------------------------------------------
inline const std::vector<std::byte> F_I_ping_request_payload =
    bytes({0x00, 0x0B, 0x08, 0x2A, 0x10, 0x01, 0x1A, 0x02, 0xDE, 0xAD});
inline const std::vector<std::byte> F_I_ping_request_frame =
    bytes({0x00, 0x07, 0x00, 0x0A, 0x00, 0x0B, 0x08, 0x2A, 0x10, 0x01, 0x1A, 0x02, 0xDE, 0xAD});

// ---------------------------------------------------------------------------
// F-J PingResponse (control 0x000C, HU -> phone) - SPEC MINIMAL FORM
// Derivation: PingResponse{f1 timestamp=42} with optional f2 data ABSENT
// (oaa/control/ControlMessageIdsEnum.proto:24; body schema per pinned AASDK
// PingResponse.proto: `required int64 timestamp = 1; optional bytes data = 2;`).
// Proto2 canonical encoding omits absent optional fields: 08 2A only.
// ---------------------------------------------------------------------------
inline const std::vector<std::byte> F_J_ping_response_payload =
    bytes({0x00, 0x0C, 0x08, 0x2A});
inline const std::vector<std::byte> F_J_ping_response_frame =
    bytes({0x00, 0x07, 0x00, 0x04, 0x00, 0x0C, 0x08, 0x2A});

// ---------------------------------------------------------------------------
// F-J2 PingResponse - OUR ENCODER FORM (explicit-empty data), CONTESTED BYTES
// (discrepancy D24). Derivation: the project value PingResponse{42, {}} maps
// to wire `set_data("")`, which proto2 serializes as present-but-empty
// f2 = 12 00, so our encoder emits 00 0C 08 2A 12 00 instead of the minimal
// F-J form. Both forms are wire-legal and decode to the same value; the
// BYTES differ. The encoder behavior is accepted task-15 content and is NOT
// changed here: the spec pins both forms and the tests fail closed on drift
// of either (canonicalization is PROPOSED, see matrix D24).
// ---------------------------------------------------------------------------
inline const std::vector<std::byte> F_J2_ping_response_encoder_form_payload =
    bytes({0x00, 0x0C, 0x08, 0x2A, 0x12, 0x00});
inline const std::vector<std::byte> F_J2_ping_response_encoder_form_frame =
    bytes({0x00, 0x07, 0x00, 0x06, 0x00, 0x0C, 0x08, 0x2A, 0x12, 0x00});

// ---------------------------------------------------------------------------
// F-K UpdateUiConfigRequest, phone -> HU direction (media/video channel
// message 0x800A). THE ANCHOR (discrepancies D1/D2).
// Derivation: message id 0x800A (oaa/av/AVChannelMessageIdsEnum numbering +
// oaa/video/UpdateUiConfigRequestMessage.proto:14 "0x800A Phone->HU") and body
// f1 config = AdditionalVideoConfig{f4 ui_theme = 1 LIGHT}
//   AdditionalVideoConfig body = 20 01 -> wrapped: 0A 02 20 01.
// AASDK history calls this id MEDIA_MESSAGE_UPDATE_UI_CONFIG_REPLY; the OAA
// rulebook is explicit that NO reply is implied (oaa/av/UiConfigMessages.proto:18-19).
// The frame channel byte is the dynamic Service.id (matrix R36); 0x63 = 99.
// ---------------------------------------------------------------------------
inline const std::vector<std::byte> F_K_update_ui_config_request_800A_payload =
    bytes({0x80, 0x0A, 0x0A, 0x02, 0x20, 0x01});
inline const std::vector<std::byte> F_K_update_ui_config_request_800A_frame =
    bytes({0x63, 0x03, 0x00, 0x06, 0x80, 0x0A, 0x0A, 0x02, 0x20, 0x01});

// ---------------------------------------------------------------------------
// F-M UpdateUiConfigRequest, HU -> phone direction (0x8009): SAME body, the
// opposite direction of the same request message (oaa/video/
// UpdateUiConfigRequestMessage.proto:14; 17.3 ledger message-matrix.md:150).
// ---------------------------------------------------------------------------
inline const std::vector<std::byte> F_M_update_ui_config_request_8009_payload =
    bytes({0x80, 0x09, 0x0A, 0x02, 0x20, 0x01});
inline const std::vector<std::byte> F_M_update_ui_config_request_8009_frame =
    bytes({0x63, 0x03, 0x00, 0x06, 0x80, 0x09, 0x0A, 0x02, 0x20, 0x01});

// ---------------------------------------------------------------------------
// F-L UpdateHuUiConfigResponse (0x8012, HU -> phone) - the TRUE reply of the
// UI-config exchange, absent from the pinned AASDK schema entirely.
// Derivation: oaa/video/UpdateHuUiConfigResponse.proto:15-26: f1 status enum
// THEMING_TOKENS_ACCEPTED = 1 -> 08 01.
// ---------------------------------------------------------------------------
inline const std::vector<std::byte> F_L_update_hu_ui_config_response_8012_payload =
    bytes({0x80, 0x12, 0x08, 0x01});
inline const std::vector<std::byte> F_L_update_hu_ui_config_response_8012_frame =
    bytes({0x63, 0x03, 0x00, 0x04, 0x80, 0x12, 0x08, 0x01});

// ---------------------------------------------------------------------------
// F-N AVChannelSetupRequest (AV channel 0x8000, phone -> HU)
// Derivation: oaa/av/AVChannelSetupRequestMessage.proto:22-24: f1
// media_codec_type = H264_BP(3) -> 08 03. (Pinned AASDK Setup.type=1 matches.)
// ---------------------------------------------------------------------------
inline const std::vector<std::byte> F_N_av_setup_request_8000_payload =
    bytes({0x80, 0x00, 0x08, 0x03});
inline const std::vector<std::byte> F_N_av_setup_request_8000_frame =
    bytes({0x63, 0x03, 0x00, 0x04, 0x80, 0x00, 0x08, 0x03});

// ---------------------------------------------------------------------------
// F-O AVChannelSetupResponse OK (0x8003, HU -> phone) - the unambiguous core.
// Derivation: oaa/av/AVChannelSetupResponseMessage.proto:21-23: f1
// media_status = OK(2). Value 2 is the ONLY status both rulebooks read as
// success (OAA OK=2 == AASDK READY=2); value 1 is contested (F-O2/D4).
// ---------------------------------------------------------------------------
inline const std::vector<std::byte> F_O_av_setup_response_8003_ok_payload =
    bytes({0x80, 0x03, 0x08, 0x02});
inline const std::vector<std::byte> F_O_av_setup_response_8003_ok_frame =
    bytes({0x63, 0x03, 0x00, 0x04, 0x80, 0x03, 0x08, 0x02});

// ---------------------------------------------------------------------------
// F-O2 AVChannelSetupResponse status=1 - CONTESTED BYTES (discrepancy D4).
// Derivation: same message, f1 = 1. OAA reads 1 as FAIL
// (oaa/av/AVChannelSetupStatusEnum.proto:17); pinned AASDK reads 1 as WAIT
// (media/shared/message/Config.proto:8). The bytes are unambiguous; their
// MEANING is contested. Our future emit path must never produce these; the
// fixture pins them so the conflict cannot be silently "resolved" by drift.
// ---------------------------------------------------------------------------
inline const std::vector<std::byte> F_O2_av_setup_response_8003_contested_payload =
    bytes({0x80, 0x03, 0x08, 0x01});
inline const std::vector<std::byte> F_O2_av_setup_response_8003_contested_frame =
    bytes({0x63, 0x03, 0x00, 0x04, 0x80, 0x03, 0x08, 0x01});

// ---------------------------------------------------------------------------
// F-P AVChannelStartIndication (0x8001, phone -> HU)
// Derivation: oaa/av/AVChannelStartIndicationMessage.proto:23-28:
//   f1 session = 1   -> 08 01
//   f2 config = 0    -> 10 00
//   f3 session_type = 1 (NORMAL) -> 18 01   [ALTERNATE(2) is PDK>=5.0 - GAL OFF]
//   f4 media_config deliberately ABSENT (PDK>=5.0 audio / >=6.0 video - GAL OFF)
// ---------------------------------------------------------------------------
inline const std::vector<std::byte> F_P_av_start_indication_8001_payload =
    bytes({0x80, 0x01, 0x08, 0x01, 0x10, 0x00, 0x18, 0x01});
inline const std::vector<std::byte> F_P_av_start_indication_8001_frame =
    bytes({0x63, 0x03, 0x00, 0x08, 0x80, 0x01, 0x08, 0x01, 0x10, 0x00, 0x18, 0x01});

// ---------------------------------------------------------------------------
// F-Q AVChannelStopIndication (0x8002, phone -> HU) - EMPTY body.
// Derivation: oaa/av/AVChannelStopIndicationMessage.proto:21-23 (message {}).
// ---------------------------------------------------------------------------
inline const std::vector<std::byte> F_Q_av_stop_indication_8002_payload =
    bytes({0x80, 0x02});
inline const std::vector<std::byte> F_Q_av_stop_indication_8002_frame =
    bytes({0x63, 0x03, 0x00, 0x02, 0x80, 0x02});

// ---------------------------------------------------------------------------
// F-R VideoFocusRequest (0x8007, phone -> HU)
// Derivation: oaa/video/VideoFocusRequestMessage.proto:11-17: NO field 1;
//   f2 focus_mode = PROJECTED(1) -> 10 01
//   f3 focus_reason = LAST_MODE(3) -> 18 03   <-- value 3 exists on the wire
//   (oaa/video/VideoFocusReasonEnum) but is MISSING from the pinned AASDK
//   VideoFocusReason enum (0/1/2 only) - discrepancy D5: proto2 would silently
//   default it to 0. The fixture pins the real value so the gap cannot hide.
// ---------------------------------------------------------------------------
inline const std::vector<std::byte> F_R_video_focus_request_8007_payload =
    bytes({0x80, 0x07, 0x10, 0x01, 0x18, 0x03});
inline const std::vector<std::byte> F_R_video_focus_request_8007_frame =
    bytes({0x63, 0x03, 0x00, 0x06, 0x80, 0x07, 0x10, 0x01, 0x18, 0x03});

// ---------------------------------------------------------------------------
// F-S VideoFocusIndication (0x8008, HU -> phone)
// Derivation: oaa/video/VideoFocusIndicationMessage.proto:14-17:
//   f1 focus_mode = PROJECTED(1) -> 08 01
//   f2 unrequested = false       -> 10 00
// ---------------------------------------------------------------------------
inline const std::vector<std::byte> F_S_video_focus_indication_8008_payload =
    bytes({0x80, 0x08, 0x08, 0x01, 0x10, 0x00});
inline const std::vector<std::byte> F_S_video_focus_indication_8008_frame =
    bytes({0x63, 0x03, 0x00, 0x06, 0x80, 0x08, 0x08, 0x01, 0x10, 0x00});

// ---------------------------------------------------------------------------
// F-T NavigationFocusRequest (control 0x000D, phone -> HU)
// Derivation: oaa/navigation/NavigationFocusRequestMessage.proto:34-36:
// f1 type = NAV_FOCUS_PROJECTED(2) -> 08 02.
// ---------------------------------------------------------------------------
inline const std::vector<std::byte> F_T_nav_focus_request_000D_payload =
    bytes({0x00, 0x0D, 0x08, 0x02});
inline const std::vector<std::byte> F_T_nav_focus_request_000D_frame =
    bytes({0x00, 0x07, 0x00, 0x04, 0x00, 0x0D, 0x08, 0x02});

// ---------------------------------------------------------------------------
// Dynamic channel byte used for the media/UI fixtures (Service.id 99). The
// frame channel byte is session-dynamic (matrix R36); 99 matches the video
// service id used across the task-20 replay tests. NEVER a static ordinal.
// ---------------------------------------------------------------------------
inline constexpr std::uint8_t kDynamicVideoServiceByte = 99;

// Contested/anchor byte-pattern presence checks used by tests.
[[nodiscard]] inline bool contains_subsequence(std::span<const std::byte> hay,
                                               std::span<const std::byte> needle) {
    if (needle.size() > hay.size()) {
        return false;
    }
    for (std::size_t i = 0; i + needle.size() <= hay.size(); ++i) {
        bool match = true;
        for (std::size_t j = 0; j < needle.size(); ++j) {
            if (hay[i + j] != needle[j]) {
                match = false;
                break;
            }
        }
        if (match) {
            return true;
        }
    }
    return false;
}

} // namespace conformancewire
